# Chaz's imports from ~/.bashrc
alias cl='clear'
alias h='history | grep '
# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias bd='cd "$OLDPWD"'
alias root='cd ~'
alias doc='cd ~/Documents'
alias pro='cd ~/Projects'
alias pic='cd ~/Pictures'
alias dow='cd ~/Downloads'
alias bak='cd ~/Backups'
# Actions
alias chx='chmod +x'
alias chax='chmod a+x'
alias 000='chmod -R 000'
alias 644='chmod -R 644'
alias 666='chmod -R 666'
alias 755='chmod -R 755'
alias 777='chmod -R 777'
# Applications
alias v='nvim .'
alias vim='nvim'
alias vimdiff='nvim -d'
alias tree='tree -C'
# alias fzf='fzf --layout=reverse --height=80%'
alias k='kubectl'
alias hr='herdr'
alias tr='tuicr'
# Personal
alias rr='reporoot'
